sudo: required
services:
  - docker

before_install:
  - docker build -t speedrunzz/docker-react -f Dockerfile.dev .

script:
  - docker run speedrunzz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-454745578886"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"